---
- name: Installation of Gnome-tweaks
  hosts: localhost
  become: true
  tasks:
    - name: Install Gnome-Tweaks
      yum:
        name: gnome-tweaks
        state: present

- name: Gnome-Tweaks Settings
  hosts: localhost
  remote_user: student

  tasks:
    - name: Complete Gnome-Tweaks Settings for Extensions
      command: gsettings set org.gnome.shell enabled-extensions "['apps-menu@gnome-shell-extensions.gcampax.github.com', 'desktop-icons@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'quiet-shortcuts@fourdan.gmail.com', 'window-list@gnome-shell-extensions.gcampax.github.com']"

    - name: Complete Gnome-Tweaks Settings for Windows
      command: gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'
