---
- name: Configure TMUX for Multi-Users
  hosts: localhost
  remote_user: student

  tasks:
    - name: Create and ensure directory
      ansible.builtin.file:
        path: /home/student/.config/tmux
        state: directory

    - name: Copy configuration file 
      ansible.builtin.copy:
        src: ../config_files/tmux.conf
        dest: /home/student/.config/tmux/tmux.conf
    



