---
- name: Configure TMUX for Multi-Users
  hosts: localhost
  remote_user: student

  tasks:
    - name: Create and ensure directory
      ansible.builtin.file:
        path: /home/student/.config/tmux
        state: directory

    - name: Copy configuration file 
      ansible.builtin.copy:
        src: ../config_files/tmux.conf
        dest: /home/student/.config/tmux/tmux.conf

    - name: Check if the TMUX Socket Exists
      stat:
        path: /tmp/tmux_socket
      register: tmux_socket_stat

    - name: Show Status of TMUX Socket 
      ansible.builtin.debug:
        var: tmux_socket_stat

    - name: Start tmux session - New TMUX Session
      ansible.builtin.shell: script -q -c "tmux -S /tmp/tmux_socket new -s student-ssh" /dev/null
      async: 30
      poll: 0
      register: tmux_start_result
      when: tmux_socket_stat.stat.exists == false

    - name: Start tmux session - Existing TMUX Session
      ansible.builtin.shell: script -q -c "tmux -S /tmp/tmux_socket att -t student-ssh" /dev/null
      async: 30
      poll: 0
      register: tmux_start_result
      when: tmux_socket_stat.stat.exists

    - name: Wait for tmux to start
      ansible.builtin.async_status:
        jid: "{{ tmux_start_result.ansible_job_id }}"
      register: tmxu_started
      until: tmxu_started.finished
      retries: 30
      delay: 1

    - name: Attach to tmux session
      shell: echo "Run ./tmux_connect.sh"
      when: tmxu_started.finished

#    - name: Start Instructor TMUX Connection
#      ansible.builtin.debug: 
#        msg: Run the command "tmux -S /tmp/tmux_socket new -s student-ssh"
#      when: tmux_socket_stat.stat.exists == false

#    - name: Start Instructor TMUX Connection
#      ansible.builtin.debug: 
#        msg: Run the command "tmux -S /tmp/tmux_socket att -t student-ssh"
#      when: tmux_socket_stat.stat.exists
