---
- name: Configure TMUX for Multi-Users
  hosts: localhost
  remote_user: student

  tasks:
    - name: Create and ensure directory
      ansible.builtin.file:
        path: /home/student/.config/tmux
        state: directory

    - name: Copy configuration file 
      ansible.builtin.copy:
        src: ../config_files/tmux.conf
        dest: /home/student/.config/tmux/tmux.conf

    - name: Check if the TMUX Socket Exists
      stat:
        path: /tmp/tmux_socket
      register: tmux_socket_stat

    - name: Show Status of TMUX Socket 
      ansible.builtin.debug:
        var: tmux_socket_stat

    - name: Start tmux session
      expect:
        command: tmux -S /tmp/tmux_socket new -s student-ssh
        responses:
          ".*": ""
      register: tmux_start_result
      when: tmux_socket_stat.stat.exists == false

    - name: Start tmux session
      expect:
        command: tmux -S /tmp/tmux_socket att -t student-ssh
        responses:
          ".*": ""
      register: tmux_start_result
      when: tmux_socket_stat.stat.exists

    - name: Attach to tmux session
      shell: tmux attach-session -t my_session
      when: tmux_start_result|success

#    - name: Start Instructor TMUX Connection
#      ansible.builtin.debug: 
#        msg: Run the command "tmux -S /tmp/tmux_socket new -s student-ssh"
#      when: tmux_socket_stat.stat.exists == false

#    - name: Start Instructor TMUX Connection
#      ansible.builtin.debug: 
#        msg: Run the command "tmux -S /tmp/tmux_socket att -t student-ssh"
#      when: tmux_socket_stat.stat.exists

