# Workflow name
name: Build PDF


# Controls when the workflow will run
# Workflow will run on a push event.
# Workflow won't be triggered to re-run based on the Gitauth token push
#on: 
  # This is a reusable workflow
#  workflow_dispatch:
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:

      # In this job, all steps begin with a name
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Podman Build Book
        run: bash ./adocpdf.sh README.adoc

#      - name: Podman Build Book
#        run: podman run --name adocpdf --rm  -e "-a pdf-theme=/opt/asciidoc/themes/tm-gls-redhat-theme.yml" -e "book_name=Main.adoc" -v $(pwd):/tmp/coursebook:Z quay.io/tmichett/asciidocpdf:latest

      - name: Copy Instructions
        run: cp README.pdf Instructions.pdf

      - name: Podman Build HTML Pages
        run: podman run --name adochtml --rm -v $(pwd):/tmp/ADOC_Work:Z quay.io/tmichett/adoc-html:latest README.adoc

      - name: Copy HTML
        run: cp README.html ./docs/index.html

      - name: Copy Images
        run: cp images/* ./docs/images

      - name: Commit and Add Book
        run: git config --global user.email "tmichett@redhat.com" && git config --global user.name "Travis Michette" && git add Instructions.pdf ./docs/index.html && git commit -m "Added new Instructions.pdf" && git push
